# Generated by Django 4.0.4 on 2022-08-11 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='dislike',
            new_name='dislikes',
        ),
    ]
